// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(HintdbContext))]
    [Migration("20231016212813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.Hint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PuzzleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sit on the chair!",
                            Order = 1,
                            PuzzleId = 1
                        });
                });

            modelBuilder.Entity("API.Entities.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Puzzles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Player must sit on the wizard's chair",
                            Name = "Sit on Chair",
                            Order = 1,
                            RoomId = 4
                        });
                });

            modelBuilder.Entity("API.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameGraphic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://paniqescaperoom.com/img/paniq/room-bg-the-time-machine-card-2.webp",
                            Name = "Time Machine",
                            NameGraphic = "https://paniqescaperoom.com/img/paniq/room-name-the-time-machine-2.png"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://paniqescaperoom.com/img/paniq/room-bg-atlantis-rising-card-2.webp",
                            Name = "Atlantis",
                            NameGraphic = "https://paniqescaperoom.com/img/paniq/room-name-atlantis-rising-2.png"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://paniqescaperoom.com/img/paniq/room-bg-haunted-manor-card-2.webp",
                            Name = "Haunted",
                            NameGraphic = "https://paniqescaperoom.com/img/paniq/room-name-haunted-manor-2.png"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://paniqescaperoom.com/img/paniq/room-bg-wizard-trials-card-2.webp",
                            Name = "Wizard",
                            NameGraphic = "https://paniqescaperoom.com/img/paniq/room-name-wizard-trials-2.png"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://paniqescaperoom.com/img/paniq/room-bg-zombie-outbreak-card-2.webp",
                            Name = "Zombie",
                            NameGraphic = "https://paniqescaperoom.com/img/paniq/room-name-zombie-outbreak-2.png"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://paniqescaperoom.com/img/paniq/room-bg-casino-heist-card-2.webp",
                            Name = "Casino",
                            NameGraphic = "https://paniqescaperoom.com/img/paniq/room-name-casino-heist-2.png"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://paniqescaperoom.com/img/paniq/room-bg-the-morning-after-card-2.webp",
                            Name = "Morning After",
                            NameGraphic = "https://paniqescaperoom.com/img/paniq/room-name-the-morning-after-2.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
